Awesome books: a complete website with navigation
carlos-ssh/Lib2.0 pull request #4
Opened 2021-08-13 23:25 UTC by carlos-ssh

- Give style to list books and add classes to javascript.
- Add style to the navbar and the name of the project.
- Add style to the form.
- Add style to the form.
- Add links and add a footer.
- Fixed footer position.
- Add a section for timer.
- Add functions SPA.
- Fixed issues on link pages.
- Aligned contact section.

2021-08-13 23:42 UTC, rloterh requested changes
Hi Juliana, 

You did extremely great on this project!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 

## Good Points 👍  
- Nice UI design
- Good ReadMe
- No linter errors


## Required Changes ♻️
- [ ] _Kindly check the comments under the review._


Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 23:42 UTC, rloterh commented on index.html
> +            <a class="nav-link active" href="#" onclick='displaySection("contact");'>Contact</a>
- [ ] The right menu elements in your navbar is missing the dividers between each menu element, as can be seen in the provided [wireframe design](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m4_full_website.md). Kindly ensure to improve upon this aspect in your design, as we really want our designs to as much as possible mimic the provided wireframe template.
- [ ] To enhance the user experience of this design kindly ensure that an active menu link is highlighted(color change or change in opacity). In other words, the current active page should have the corresponding menu item highlighted.

**Your design menu:**
![image](https://user-images.githubusercontent.com/12745474/129427177-5cc64b6d-0470-44b7-898d-3c4ab4eb40ec.png)


**The wireframe menu design:**
![image](https://user-images.githubusercontent.com/12745474/129183812-a30acaa9-4f6c-4d4e-973b-5dd83a591c8d.png)


- [ ] OPTIONAL
It will be a nice idea to structure your menu items using the `ul` and `li` tags

2021-08-13 23:51 UTC, carlos-ssh commented on index.html
> +            <a class="nav-link active" href="#" onclick='displaySection("contact");'>Contact</a>
- removed active parameter for all links and just left the List as and active.
- added separators between links.

2021-08-14 00:01 UTC, sinansevgi approved these changes
# Approved :heavy_check_mark: 

Hi @carlos-ssh ,

Great work on making changes requested by the previous TSE. 
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 00:04 UTC, merged